# Generated by Django 3.2.7 on 2021-09-23 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualCurrencyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update datetime')),
                ('bank', models.CharField(max_length=15, verbose_name='Bank name')),
                ('city', models.CharField(max_length=7, verbose_name='Regional city')),
                ('usd_buy', models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='Buy USD')),
                ('usd_sell', models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='Sale USD')),
                ('euro_buy', models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='Buy EUR')),
                ('euro_sell', models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='Sale EUR')),
                ('rub_buy', models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='Buy RUB')),
                ('rub_sell', models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='Sale RUB')),
                ('usd_buy_from_euro', models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='Buy USD from EUR')),
                ('usd_sell_from_euro', models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='Sale USD from EUR')),
            ],
            options={
                'verbose_name': 'Actual currency info',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update datetime')),
                ('telegram_id', models.PositiveIntegerField(verbose_name='User telegram ID')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Last name')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Telegram user',
                'verbose_name_plural': 'Telegram users',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update datetime')),
                ('text', models.TextField(verbose_name='Message text')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='telegram_bot.telegramuser', verbose_name='User message')),
            ],
            options={
                'verbose_name': "User's message",
                'verbose_name_plural': "User's messages",
            },
        ),
    ]
