# Generated by Django 3.2.7 on 2021-09-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualcurrencyinfo',
            name='bank',
            field=models.CharField(max_length=255, verbose_name='Bank name'),
        ),
    ]
