# Generated by Django 3.2.7 on 2021-09-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_alter_actualcurrencyinfo_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.CharField(max_length=255, verbose_name='User telegram ID'),
        ),
    ]
