# Generated by Django 3.2.7 on 2022-04-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_alter_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update datetime')),
                ('is_beat_weather', models.BooleanField(default=True, verbose_name='Beat sending weather info')),
                ('is_beat_currency', models.BooleanField(default=True, verbose_name='Beat sending currency info')),
                ('telegram_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='settings', to='telegram_bot.telegramuser', verbose_name='User settings')),
            ],
            options={
                'verbose_name': 'User settings',
                'verbose_name_plural': "User's settings",
            },
        ),
    ]
