# Generated by Django 3.2.7 on 2022-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_telegramusersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='city_location',
            field=models.CharField(max_length=50, null=True, verbose_name='City location'),
        ),
    ]
