# Generated by Django 3.2.7 on 2022-04-27 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_telegramuser_city_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusersettings',
            name='telegram_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='telegram_bot.telegramuser', verbose_name='User settings'),
        ),
    ]
